version: '3.8'


services:
  node:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_USERNAME: admin  
      MONGO_DB_PWD: password
      DATABASE_NAME: my-db
      MONGO_URL: 'mongodb://admin:password@mongodb:27017'
    depends_on:
      - mongodb
    networks:
      - app_net

 # here it is not necessary to keep username and password in env variable cause in server.js there is no any environment vairable mention, 
 # so to connect to db it use Mongourl as it is mention is server.js*/


  mongodb:
    image: mongo:4.4
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my-db
    volumes:
      - mongo-data:/data/db
    networks:
      - app_net

   

    
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports: 
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - app_net




volumes:
  mongo-data:
    driver: local

networks:
  app_net:      
    driver: bridge
